version: "3"
services:
    morpher-api:
        image: szgabsz91/morpher-api:1.8.0
        container_name: morpher-api
        hostname: morpher-api
        ports:
            - 8080:8080
    
    morpher-client:
        image: szgabsz91/morpher-client:2.1.0
        container_name: morpher-client
        hostname: morpher-client
        ports:
            - 80:80
        depends_on:
            - morpher-api
